# Generated by Django 4.2.2 on 2025-05-30 12:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerifyCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱地址')),
                ('code', models.CharField(max_length=6, verbose_name='验证码')),
                ('type', models.CharField(default='1', max_length=1, verbose_name='验证码类型')),
            ],
            options={
                'verbose_name': '邮箱验证码表',
                'verbose_name_plural': '邮箱验证码表',
                'db_table': 't_email_verify_code',
            },
        ),
    ]
